repos:
- repo: https://github.com/doublify/pre-commit-rust
  rev: eeee35a89e69d5772bdee97db1a6a898467b686e # v1.0 tag
  hooks:
    - id: fmt
      name: Rust Formatter Check
    - id: clippy
      name: Rust Linter Check
      args: ["--all-targets", "--", "-D", "warnings"]
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.13.0 # Specify a pinned, stable version
  hooks:
    - id: commitlint
      stages: [commit-msg]
      additional_dependencies: ['@commitlint/config-conventional'] # Use conventional commit rules