repos:
- repo: local
  hooks:
    - id: rustfmt
      name: Rust Formatter Check
      entry: cargo fmt -- --check
      language: system
      types: [rust]
      pass_filenames: false # Run against the whole project state if any .rs file changed
    - id: clippy
      name: Rust Linter Check
      entry: cargo clippy --all-targets -- -D warnings # Fail on any warnings
      language: system
      types: [rust]
      pass_filenames: false