# .pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Use the latest stable version
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-merge-conflict
-   repo: local
    hooks:
    -   id: cargo-fmt-check
        name: cargo fmt --check
        entry: cargo fmt --check --
        language: system
        types: [rust]
        pass_filenames: false # Run on the whole project if any Rust file changed
    -   id: cargo-clippy
        name: cargo clippy
        # Allow dead_code warnings for now, but keep strict settings for others
        entry: cargo clippy -- -A dead_code
        language: system
        types: [rust]
        pass_filenames: false # Run on the whole project if any Rust file changed