repos:
- repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
  hooks:
    - id: fmt
      name: Rust Formatter Check
    - id: clippy
      name: Rust Linter Check
      args: ["--all-targets", "--", "-D", "warnings"]
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.13.0 # Specify a pinned, stable version
  hooks:
    - id: commitlint
      stages: [commit-msg]
      additional_dependencies: ['@commitlint/config-conventional'] # Use conventional commit rules